### ISSUE TITLE
API Authorization and Authentication

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#110]
How will we authenticate users to our API and how will they be authorized to perform certain actions?

**Comment by whereismyjetpack** [comment]
We may want 2 different classes of API authentication, or maybe just the one.

For non-humans, we probably want non-human accounts in the user model, and we probably want to signify somehow that they are a service account via a table, or convention. i.e `sa-metadata-database` for the token the metadata-database will use. or a table `is_robot?`
For this class of user, we probably want users and tokens generated by scholarsphere admins to hand out to the admins of the dependant services ( we could potentally open this up to standard users, too??) 

something like https://github.com/gonzalo-bulnes/simple_token_authentication would work for this.

For humans, we could use the same strategy, or we could use something like `tiddle` or `devise-jwt` to have shorter lived, renewable tokens 

https://github.com/waiting-for-dev/devise-jwt
https://github.com/adamniedzielski/tiddle

I think coming up with the non-human path would be step #1 and then we can see if we need something more elegant for humans?
