### ISSUE TITLE
Investigate mulitpart upload process for API

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#114]
Uploading files via the API should be able to use a multipart process, as opposed to a direct upload endpoint. (#108) This would be required for large files that are unable to be sent via a one post action.

## WDLL

Investigate how we would send files to S3 in an API environment, such as command line, using multipart, and then send the resulting metadata in the post request to create the file object in Scholarsphere.

This does not require a complete sketch or PR, but sample code would be ideal, or detailed explanations of process and/or additional tickets outlining the additional work required.

**Comment by whereismyjetpack** [comment]
Rough outline of steps for a multipart upload (this assumes the work has already been created)
Quick and dirty method:
1.) Post to `/s3/multipart` with the following params
```
{"filename":"Screen Shot 2019-11-12 at 10.01.43 AM.png","type":"image/png","metadata":{"name":"Screen Shot 2019-11-12 at 10.01.43 AM.png","type":"image/png"}}
```
You will get the following response 
```
resp =  {"uploadId":"c49c710b-84ff-45cd-8c92-0d5ea20fcb8c","key":"cache/2766a0e0158e36a40f6da9926e853505.png"}
```

2.) Upload file to s3 at location of resp['key']

3.) Post to `/s3/multipart/#{resp['uploadId']}/complete/?key=#{resp['key']}`

(this part might require sending etag, and part number as part of params / payload.

4.) finish editing work with `value='{"id":"1110bd1fb0051ee3d1f0f2aefdcf0222.png","storage":"cache","metadata":{"size":10913,"filename":"Screen Shot 2019-11-12 at 10.01.43 AM copy.png","mime_type":"image/png"}}'` as a work_version[file_rsource_attribute] (this is currently a hidden form field.)
