### ISSUE TITLE
Implement embargoes and leases

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#120]
Works should be able to be embargoed, meaning they are restricted until such a time that they are then less restricted. Conversely, leases should be able to allow access until such a time when the work become more restricted.

## What is an embargo?

An embargo in Scholarsphere 4 differs from the existing concept in Scholarsphere 3. In Scholarsphere 4, and embargo means a work's file content is not available until after a specified date. It is also not _discoverable_ in a search result. **However, its URL will still resolve!**

## Implications

* all the functionality can be accomplished by referencing the date of the embargo
* no need to "expire" embargoes
* no need to keep records of expiration or activation

## TODO
* architect persisting and managing leases and embargoes
* enforce leases and embargoes using ACLs
* ~~ensure that each are expired correctly with the ACLs modified accordingly~~
* ~~build UI components for apply leases and embargoes to works~~
  * embargoes will be created via "backend" procedures

## Questions
* do we need leases or just embargoes? _Just embargoes_
* what level of granularity do we need, i.e. only non-public to public embargoes, or is the shift in permissions more finite, such as restricted to registered, or one group's access to a different group's access?
  * since an embargo only affects file content, it is separate from permissions. A work's permissions and visibility will be what they are, and the embargo will only affect the downloading of content. So a work could be Penn State only and embargoed, or public and embargoed.

**Comment by awead** [comment]
Capturing some discussion from @rschenk and I:

One way to do this would be to put a date range on a specific ACL so that its presence, and therefore its enforcement, depends on the day and time. So in the case of an embaro, an ACL that _restricts_ access is only effective **until** X date, and then other ACL that _enables_ access is only effective until **after** X date. Leases would work the same way, just reversed: the enabling ACL is in effect until X, and then the limiting ACL is in effect after X.

However, if we need to make them more explicit, and provide additional metadata about them such as who put it there, when it was actually expired, etc. we would need a separate database resource to capture that information. The downside with that is that we would need a process that goes around and expires the lease or embargo, and changes the ACLs associated with the resource.

**Comment by DanCoughlin** [comment]
We will not implement leases, Seth and Adam will work to figure out how to handle the one existing lease that exists. We will implement embargoes, and Seth and Brianna will work on what that embargo means in terms of permissions being changed, is metadata always viewable and what changes when the embargo is up.

**Comment by srerickson** [comment]
A quick rundown of how a few repositories/repository tools handle access to metadata of embargoed materials: 

- dryad: "Previously, we gave the option to temporarily embargo both the files and the metadata, OR to temporarily embargo the files only. Now, we only do the latter. We also made it so that most embargoes have to be requested via our help desk, rather than being applied automatically or giving the author the option to select an embargo in the submission system. This has cut down on our # of embargoes dramatically" (from personal correspondence).

- bepress:  "When an embargo is applied to a submission, the metadata page displays a notice below the Download button informing visitors of the embargo expiration date." ([link](https://www.bepress.com/reference_guide_dc/access-control/#differences-between-embargoes-and-access-control))

- dspace: "Embargoes can be applied per item (including metadata) and per bitstream (i.e. file). The item level embargo will be the default for every bitstream, although it could be customized at bitstream level." ([link](https://wiki.lyrasis.org/display/DSDOC6x/Embargo))

**Comment by srerickson** [comment]
After a discussion at standup this morning, the direction we seem be leaning is to __treat an embargo as a temporary restriction on files but not metadata__. The arguments for this approach are:

- This behavior reflects most implementations of embargoes described above.
- This is also how embargoes work in PSU's ETD system and it's good to be consistent.
- It reflects the use case of an embargoed work being a "published" work with a resolvable DOI, but with restricted content. (NB: the publication date of an embargoed work is *not* the date when the embargo is lifted; it's the data when the embargo period starts.)

The main argument against is that this approach deviates from current SS3 behavior, in which embargoes are restrictions on both files and metadata. But this doesn't seem like an insurmountable obstacle.

Some additional points that came up in our discussion: 

There is some interest in following the lead of Dryad and Anonymous University A (above) and removing embargoes as a user-facing option: For example, users might requests embargoes through a ServiceNow-based form. Certainly, we don't want to promote and encourage embargoes in the UI. Embargoes should be an "advanced" option if they are in the UI at all.

An additional question to consider is whether the metadata record of an embargoed work should appear in search results. This requires more discussion.

**Comment by DanCoughlin** [comment]
How handle existing embargoes and leases

- Seth is going to notify people that there is a slight change from ScholarSphere and if that is a problem, they will contact Seth. Adam will provide a list of these (things that have embargoes)

Will embargoes and leases be available through public user UI

- The extent of the UI will be a link to a SNow ticket and from there we can create something on the back end. 

We are not concerned with a record of the fact that at one point there was an embargo
