### ISSUE TITLE
Investigate deploying FITS as a lamda

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#123]
Related to #121, we could also run FITS in AWS as a lamda, or essentially a script, that run fits on a given file and then POSTs the resulting data to Scholarsphere via the API.

**Comment by awead** [comment]
# Solutions

## Simplest: Layered Lambda

* create a new directory in the S3 bucket for files "promoted" by Shrine
* lambda triggers on any file copy to directory prefix
* attach a layer containing the FITS executable to the lambda
* when triggered, the lambda "shells out" to the FITS script provided by the layer
* xml results are written _back to a directory in the bucket_ to be harvested or indexed later

### Pros and Cons

* least number of moving parts
* potentially least performant because of the call to the FITS executable
* lambda's memory limits for large files? (potential deal-breaker)
* Scholarsphere won't know when the FITS output is available

## Layered Lambda with API integration

* same as above, except FITS output is posted back to Scholarsphere's API

### Pros and Cons

* potentially least performant because of the call to the FITS executable
* lambda's memory limits for large files? (potential deal-breaker)
* Scholarsphere is given the data, instead of having to go find it
* AWS -> SS connection details are unknown
* creates a "public" API endpoint between AWS and Scholarsphere

## Lambda with FITS Servlet

* create a new directory in the S3 bucket for files "promoted" by Shrine
* lambda triggers on any file copy to directory prefix
* lambda sends file to FITS servlet endpoint (likely also deployed in AWS)
* results are either written back to the bucket, or posted to Scholarsphere's API

### Pros and Cons

* most complex scenario
* best possible FITS performance, assuming internal data transfers between the bucket and AWS-hosted services are optimized
* files must still be sent out to FITS service
* ideally would require creating a streamed connect to the FITS servlet, which is an unknown

**Comment by DanCoughlin** [comment]
@whereismyjetpack thinks we will need to have a control loop that runs in AWS and then sends this information back from FITS when complete by hitting a ScholarSphere API to update the metadata.

May have FITS and virus scanning in the same mechanism. @whereismyjetpack to look into both in new year.
