### ISSUE TITLE
Visibility groups

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#132]
Scholarsphere has the notion of "visibility" which is a application-wide type of permission that can encompass multiple types of permission, but is currently used for two main kinds of access: public, and registered. Public access is identical to Open Access, meaning anyone can access a record's metadata and download its content. Registered access means that the user must be "registered" with the application, or logged in. This translates to institutional access, or anyone with valid Penn State credentials.

These two kinds of permissions are implemented as groups: "public" for open access, and "registered" for Penn State access.

We also have "private" visibility to denote a work that is only accessible to the depositor, but this has been disabled as a UI option because of open access considerations. We could continue to use it, or remove it entirely.

## WDLL

* define in the application two groups for public and registered access
* ensure that these groups are seeded in the groups table
* groups should be notated in such a way that their values, ex. public and registered, are inconsequential, i.e. no "magic strings"
* a group's name should be able to be communicated to the user in a different way, ex. the "public" group name could be display as "Open Access"

## Questions

Note to @srerickson 

* remove the notion of "private" visibility?
* would there be a need for additional types of visibility?
* should we remove the notion of visibility entirely and solely rely on ACLs to communicate open access, PSU-access, restricted access, etc?

**Comment by srerickson** [comment]
> remove the notion of "private" visibility?

Yes.

> would there be a need for additional types of visibility?

Maybe but see below. 

> should we remove the notion of visibility entirely and solely rely on ACLs to communicate open access, PSU-access, restricted access, etc?

The usefulness of "visibility" is that it's a good way to communicate ACLs to the user. I think we should adopt visibility as a shorthand for a set of ACLs but the visibility status doesn't need to be stored as an independent metadata field. So visibility would remain as a user-facing abstractio but just be ACLs on the backend.

**Comment by awead** [comment]
@srerickson so to sum up, there is no "visibility" but instead, two groups.

## Open Access

* has an ACL of `read_groups=['public']`
* read level access is defined in #133 

## PSU Access

* has an ACL of `read_groups=['registered']`
* read level access is defined in #133

**Comment by srerickson** [comment]
I suppose this doesn't address embargo and lease which would need ACLs plus some future event to change the ACLs.

**Comment by awead** [comment]
@srerickson Right. There's a ticket here #120. @rschenk and I discussed this briefly today... I'll put that over in that ticket and we can talk about it later.
