### ISSUE TITLE
Migrating resource types to work types

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#148]
Fill out list of resource types used when creating a work.

## WDLL
* populate the drop-down list of work types using the existing list of resource types from SS3
* migrate one resource type to `Work.work_type`
* migrate ALL resource types to 1=`WorkVersion.resource_type`
* remove `resource_type` as an edit and display field (show and search result pages)
* ensure `work_type` is indexed and displayed
* map each resource type to a type in Datacite (?)
* PENDING: remove some from the Scholarsphere list @srerickson such as "masters culminating thesis"

**Comment by srerickson** [comment]
I think done looks different (DLD) at this point. Instead of remapping `resource_type` values to a new set of resource types, we should maintain consistency with SS3's resource types (and possibly remap after launch).  

A sticking point is that the `work_type` field in SS4 is single value but `resource_type` in SS3 is multivalue. We either need to remove the additional values for the ~300 Works and Collections that have multiple resource types (probably would require some manual process) or make `work_type` multi-value.

**Comment by srerickson** [comment]
with respect to mapping, we should adopt the same "resource types" used in SS3. We can remap after launch.

**Comment by awead** [comment]
@srerickson we could map a SS3 work's resource type to the work version's resource types in SS4, maintaining their cardinality, then map a single resource_type to the work's type. For the ones that have multiple values, we could either leave them in draft status, to be resolved later, or find some heuristics for picking a single type out of a group. For example, if dataset is present, just take that and move on.

FWIW, I don't really understand the _need_ for multiple types, but I believe it was to facilitate self-deposit so a user wouldn't get confused when trying to pick the type that best suited their work. 🤷‍♂️

**Comment by srerickson** [comment]
@awead this could be a good middle ground and a way to transition away from multi-value work types, which I agree is not ideal. 

As for the "heuristic", below is a list of all the unique resource type combinations. We might make a "rule" for each one to set the Work Type.
```
"Dataset,Image"
"Dataset,Image,Other"
"Dataset,Image,Other,Project"
"Dataset,Image,Project"
"Dataset,Image,Research Paper,Article"
"Dataset,Project"
"Dataset,Software or Program Code"
"Dissertation,Dataset"
"Dissertation,Image,Research Paper,Article"
"Dissertation,Research Paper"
"Image,Other,Project"
"Image,Presentation"
"Image,Video"
"Journal,Article"
"Map or Cartographic Material,Image"
"Masters Thesis,Research Paper,Capstone Project"
"Other,Article"
"Other,Conference Proceeding"
"Other,Project"
"Poster,Conference Proceeding"
"Poster,Project"
"Poster,Project,Presentation"
"Poster,Research Paper"
"Presentation,Article"
"Presentation,Audio"
"Presentation,Conference Proceeding"
"Presentation,Project"
"Presentation,Project,Poster"
"Report,Dataset"
"Report,Dataset,Presentation"
"Report,Image,Presentation,Research Paper,Project,Software or Program Code,Article"
"Report,Poster,Project"
"Report,Presentation"
"Report,Project"
"Report,Research Paper"
"Report,Thesis,Research Paper,Project,Software or Program Code,Capstone Project"
"Research Paper,Article"
"Research Paper,Software or Program Code"
"Thesis,Poster"
"Thesis,Project"
"Thesis,Project,Software or Program Code,Dissertation"
"Video,Presentation"
```

**Comment by DanCoughlin** [comment]
We are migrating resource type as a legacy field, so that will contain all the existing resource type data. We will map the work type field to the existing resource type, but we will only track one of the current values. 
ScholarSphere 3             ScholarSphere 4
Resource Type => Work Type will be a single item from Resource Type[0]
Resource Type => Resource Type (users will not see them, only keeping in case we need it later)

**Comment by DanCoughlin** [comment]
@srerickson is working on the mapping

**Comment by srerickson** [comment]
Here is the mapping (in csv format):

```
"Report,Project",Report
"Dataset,Image,Other",Dataset
"Image,Other,Project",Image
"Image,Video",Video
"Dataset,Image",Dataset
"Dissertation,Image,Research Paper,Article",Article
"Presentation,Article",Article
"Other,Project",Other
"Dissertation,Dataset",Dataset
"Report,Dataset,Presentation",Dataset
"Dataset,Software or Program Code",Software or Program Code
"Research Paper,Article",Article
"Other,Conference Proceeding",Conference Proceeding
"Dataset,Image,Other,Project",Dataset
"Dataset,Image,Research Paper,Article",Dataset
"Poster,Research Paper",Poster
"Conference Proceeding,Article",Conference Proceeding
"Presentation,Audio",Presentation
"Poster,Project,Presentation",Presentation
"Dataset,Project",Dataset
"Report,Presentation",Presentation
"Dataset,Image,Project",Dataset
"Map or Cartographic Material,Image",Map or Cartographic Material
"Masters Thesis,Research Paper,Capstone Project",Masters Thesis
"Report,Image,Presentation,Research Paper,Project,Software or Program Code,Article",Article
"Research Paper,Software or Program Code",Software or Program Code
"Poster,Conference Proceeding",Conference Proceeding
"Journal,Article",Article
"Poster,Project",Poster
"Thesis,Project,Software or Program Code,Dissertation",Software or Program Code
"Presentation,Project,Poster",Presentation
"Report,Thesis,Research Paper,Project,Software or Program Code,Capstone Project",Software or Program Code
"Presentation,Conference Proceeding",Presentation
"Thesis,Poster",Poster
"Dissertation,Research Paper",Research Paper
"Other,Article",Article
"Report,Research Paper",Report
"Thesis,Project",Thesis
"Report,Poster,Project",Poster
"Image,Presentation",Presentation
"Presentation,Project",Presentation
"Report,Dataset",Dataset

```
