### ISSUE TITLE
DOI Minting UI Component

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#150]
Provide UI elements for minting DOIs on works and work versions. @srerickson 

## WDLL

* controller to respond to link
* controller kicks off service
* service sets a pending status in Redis and enqueues job
* DOI field in UI will display status based on Redis key
* link will be greyed out
* by default, the DOI should be on the *work*

If the work doesn't have a DOI, then the DOI is on the work, regardless of what version you're looking at. You can only mint a DOI for a work version if the work already has a DOI, and you're viewing the resource page for that specific version.

**Comment by srerickson** [comment]
In case this comes up: minting a DOI for a work version should not generate a new version.

**Comment by DanCoughlin** [comment]
Closing b.c. this ticket is for wire frames and not implementation

**Comment by srerickson** [comment]
reopening for #338

**Comment by DanCoughlin** [comment]
We will create a link within the gear drop down on the Work View page.
