### ISSUE TITLE
Documentation and Policy Pages

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#167]
We need a set of pages within the ScholarSphere site that tell users what our policies are for backups, storage, etc. 

## What We Need

* names of pages, i.e. "About"
* what the link should be, i.e. `/about` 

## WDLL

* markdown pages in `/app/views/pages`
* corresponding actions in the pages controller, ex. `/about`
* updates will happen via PR and releasing

**Comment by srerickson** [comment]
There will be a few basic parts of this website:
-  Documentation and Guidelines (could be a single page but not necessarily)
-  Current Polices, Deposit Agreement, and Terms of Use (a single page)
-  Old Policies, Deposit Agreement, and Terms of Used (single page each) 

This issue does not need to involve a UI/CMS for updating these docs. For 4.0 we can just host static pages.

**Comment by srerickson** [comment]
relates to #185
