### ISSUE TITLE
Search existing creators both via LDAP and locally added creators

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#180]
Returns a list of creators taken from the local database and Penn State's identity management system.

Blocked by #93

**Comment by whereismyjetpack** [comment]
Our Friends in EIT have developed a rest-service "search-service" that may fit these needs. I'm going to be looking to see if it provides the information we need in the coming days for another project, but wanted to share here. 

Their swagger dogs are hosted here:
https://identity.apps.psu.edu/search-service/resources
