### ISSUE TITLE
Versioning Deposit Agreement

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#185]
What done looks like: 
- A way to configure the current deposit agreement used for new deposits.
- Work attribute (e.g. `deposit_agreement_version`) that indicates the version of the agreement that the depositor agreed to at the time of deposit. 
- The`deposit_agreement_version` for existing Works is set to the agreement currently used in ScholarSphere 3.
- When new deposit agreements are finalized, they can be added to ScholarSphere (through code update if necessary) and set as the current deposit agreement.
- `agreement_date` field indicating date of the deposit agreement (basically date of the first published version).

**Comment by awead** [comment]
Questions:
* do multiple versions of the agreement need to be available at the same time such that Work A can be published under Agreement v. 1, whereas Work B may be published under Agreement v. 2?
* would works be "updated" to newer deposit agreements?

**Comment by srerickson** [comment]
The answer to both your questions is no. I think I see where you're going with this: We don't need a new field for the version info if the work's deposit date is accurate and we can record which deposit agreement was active for a particular date. I suppose that could work; I also like the explicitness of a dedicated field.

**Comment by srerickson** [comment]
With the launch of 4.0, new deposits will (very likely) use a different agreement. Old works (those migrated from SS3) will continue to be linked with the old agreement. The tricky case is how to handle new versions of old works: should the agreement be updated from old to new? 

I don't think that makes sense to do since very often new versions are created by curators making metadata corrections. Changing the agreement is something the depositor needs to do. That's why I don't think the deposit agreement should be version-level metadata.  

__A change in the agreement that covers a particularly work should be thought of as a work-level action that is independent of the visioning system.__

**Comment by DanCoughlin** [comment]
Should be a field that has the deposit agreement version to know when a document was deposited with what version. We can either store a version of the policy deposited or a url to the policy version that existed when this was deposited. We can store the text version of the policy and then we will be able to convert that to a link for someone to retrieve. 

This deposit agreement is at the work level not at the version - *noted above*

**Comment by srerickson** [comment]
Following discussion with @awead, I'm adding a requirement for a `agreement_date` field indicating date of the deposit agreement.
