### ISSUE TITLE
Override Solr port

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#188]
We don't seem to be able to override the port that Solr is using in Docker. Trying an override file, as documented in https://docs.docker.com/compose/extends/, didn't work. I also tried changing the ports directly in `docker-compose.ym` but that doesn't work either. Docker starts up, but I'm seeing a lot of  lines like`coreZkRegister-1-thread-1-processing-n:172.19.0.2:8983_solr` indicating that the port might be hardcoded somewhere, or the change in the compose file isn't getting communicated all the way down.

**Comment by whereismyjetpack** [comment]
The Internal port will always be 8983, but that's OK. The port mapping in docker-compose can now accept an env var i.e 

`SOLR_PORT=8985 docker-compose up -d solr` will proxy 8985 -> 8983 internally 

`docker ps `
```
a0a1ea4de49d        solr:8.2.0-slim                                   "docker-entrypoint.s…"   2 minutes ago       Up 2 minutes        0.0.0.0:8985->8983/tcp                           scholarsphere-4_solr_1
```
