### ISSUE TITLE
Interface for viewing, searching, and editing another user's works

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#206]
When we migrate content over from Scholarsphere 3, many of the works will be in draft state because they are private, or lack the right metadata for publishing. Presently, there is no way to view these draft works unless you are logged as the depositor who originally created them.

## WDLL

A user, with the correct level of permissions such as an admin, can search for, view, and update existing draft works so that they can be published, or remain in draft state until such a time that they would be withdrawn.

**Comment by srerickson** [comment]
I don't think we need this given our current plans for the "dashboard" (my deposits page). #29

**Comment by awead** [comment]
Subsumed by #29
