### ISSUE TITLE
Download Files

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#216]
We need the ability to download individual files from a work.

## Questions
* Since the Rails app must authorize each download, does the data pass through the app to the user instead of from S3 directly?

## WDLL
* either display the file as a link which downloads it, or, have a button adjacent to it
* controller will honor ACL and policies such that the user may only download files they have access to

**Comment by whereismyjetpack** [comment]
In ss-shrine we had the view generate the presigned url for a guest to download the file; however for scholarsphere i don't know if we need to generate that presigned url _until_ a guest clicks on the link. this would prevent us from needlessly generating a bunch of calls out to the aws api.

**Comment by srerickson** [comment]
My preference would be to handle file downloads by redirecting the request to a presigned S3 URL that expires. This would keep potentially long-running requests out of the Rails app; it would help with scalabaiblity (which has been a problem in SS3); and it would leverage the capabilities of the infrastructure. 

If it's difficult or time-intensive to implement it this way, or if this falls into the category of premature optimizations, then we should at least architect the platform to make it easier to move to a presigned S3 URL if necessary.

**Comment by awead** [comment]
I think this is both overly-complicated and premature. We've had very large downloads (10-100 GB) available via current Scholarsphere in the past and it hasn't presented a problem, other than the time required to download. Routing all the downloads to a single controller would be the first step, and later if we've determined that it's necessary, we can use that same controller to handle the redirects to S3.

Regarding scalability, with the new deployment system we're using (Kubernetes), we could scale out to meet any kind of demand, whether that's more download capacity, or handling more requests in general. Downloading a file doesn't require very many system resources. The potential advantage for utilizing S3 is resumable downloads and faster throughput.

**Comment by whereismyjetpack** [comment]
Unless I'm missing something, this should be _easier_ and less error prone to do a presigned url than to route the file through the application 

Given that a user wants to download file 2 from work_version 3 and does a GET to /downloads/3/2

```
# psudo code. probs doesn't work
        if can_download?(work_version)
            s3 = Shrine.storages[file_resource.file_data['storage'].to_sym]
            url = s3.url(file_resource.file_data['id'], response_content_disposition: "attachment", expires_in: 30)
            redirect_to url
        else
            flash.alert = 'Must Be authorized in to download this file'
            redirect_back fallback_location: '/'
        end
```

is effectively the same as 
```
# psudo code. probs doesn't work
        if can_download?(work_version)
            file = s3.bucket('bucket').download('obj')
            send_data file
        else
            send_data('sad-panda.txt')
       end
```
 

My concern with routing through the rails app is effectively doubling the time required for a guest to download a file, and the container running the rails app would need enough free space to accommodate the maximum number of downloads that could happen at any given time. Also, If the download takes longer than the timeout, we're sending the guest timeout messages.

**Comment by srerickson** [comment]
@whereismyjetpack, that's helpful to see. I still like this approach (the one in the first code snippet above) but in fairness to @awead, I think his plan basically is to reverse proxy the data from S3, so there may be some buffering but no need to store the whole file; it would take as long as the slowest connection between S3 -> Rails -> User, but not necessarily twice as long. @awead is that right?
