### ISSUE TITLE
List of work-level and version-level metadata fields

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#229]
Need to document fields that can/cannot change between versions. 
This is becoming a blocker for #207

**Comment by srerickson** [comment]
@adam, is this the kind of thing that goes in an "architecture decision" document?

**Comment by awead** [comment]
@srerickson I don't think so. We've architected it so that we can have fields in different places. That would have been a decision, if we needed to document that. What we're documenting here is how it's being used, which _does_ need to go someplace... Maybe in API docs?

**Comment by DanCoughlin** [comment]
Going to move this to a more general documentation.

**Comment by srerickson** [comment]
Here is the wiki page with the breakdown of Work/Version metadata: 
https://github.com/psu-stewardship/scholarsphere-4/wiki/Architecture-Overview
