### ISSUE TITLE
Interactive UI for searching and adding creators

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#244]
Populate the work version edit form with existing creators taken from our local database and Penn State's identity API.

## WDLL
* search bar within creators that searches both sources and inserts new creators from the selection in the search bar
* UI feature parity with Scholarsphere 3 

Blocked by #242

**Comment by srerickson** [comment]
### ScholarSphere3 UI for reference:

<img width="1035" alt="Screen Shot 2020-05-27 at 12 22 37 PM" src="https://user-images.githubusercontent.com/876323/83046307-d74a9200-a014-11ea-83a8-369e5faa8efc.png">

**Comment by srerickson** [comment]
Ideally we can include a field to add an ORCID ID.
