### ISSUE TITLE
Enable DataDog Analytics for preview/migration

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#246]
While we're evaluating DataDog, we could use it to look at Scholarsphere 4 during a migration to see what it can tell us. Is it possible to set this up? I only see psu-authproxy and etda-workflow.

@whereismyjetpack, can you look into this?

**Comment by whereismyjetpack** [comment]
This is shooting metrics into the wind; but there's a few minor tweaks I want to make.

**Comment by awead** [comment]
@whereismyjetpack That's fine. Basically, I'd like to get some data into DataDog's dashboard so I can l see what it looks like. Doesn't have to be anything special.

**Comment by whereismyjetpack** [comment]
I enabled all the bits we use (faraday, redis, postgres, rails) and the thing i wanted to clear up was naming them. They should be up and running now!
