### ISSUE TITLE
DOI for collections

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#273]
Collections should be able to have a DOI assigned to them.

**Comment by DanCoughlin** [comment]
creating new DOIs for collections via the web UI will be done post-launch.

**Comment by rschenk** [comment]
Currently, collections can have a DOI assigned to them. That is, they have a field in the database to store the doi string, and they also have scholarsphere-3 legacy ID support. So right now Collections can be on the receiving end of DOIs.

We do not  yet have the capability to mint DOIs for collections. That will require writing a new metadata adapter to translate a collection's metadata to match Datacite's, similar to how we do with Work/Versions. This won't be very hard but isn't done yet.

My understanding is that for the launch of SS4, we do not need minting capability, just the ability to support existing DOIs. In that case, we are effectively done. As long as the migration code properly copies over the DOIs out of SS3 and inserts them into SS4. @awead

**Comment by awead** [comment]
Addition work ticketed in #313
