### ISSUE TITLE
Collection View Page

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#284]
Need a page for viewing a collection. For now this can be based on the current collection view page in SS3. 

![Screenshot from 2020-05-04 11-43-03](https://user-images.githubusercontent.com/876323/80984889-74dae900-8dfc-11ea-85be-5660e1d70819.png)

**Comment by DanCoughlin** [comment]
We are currently using the database record (for works and collections display). May look at changing this to be backed by Solr instead of the database post-release in order to be able to search and sort.

**Comment by rschenk** [comment]
We currently have a publicly accessible "view" page for showing a collection, it lives at `/resources/:the-uuid-of-a-collection:` and it shows the metadata for a collection along with the list of works in that collection. It's certainly not pretty. 

What does done look like with this ticket? Does it need final visual styling?

**Comment by awead** [comment]
Fixed in #473
