### ISSUE TITLE
Solr query permissions on PSU Only.

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#289]
Solr search needs to return results for works and collections that are PSU only visibility, the content would not be accessible, but the metadata is.

## WDLL

1. Add an ACL for public discovery access to Permissions#grant_authorized_access
2. Ensure that the ACL is removed with Permissions#revoke_authorized_access
3. Update WorkPolicy#show?
4. Update discovery_spec tests to ensure everything works correctly

**Comment by awead** [comment]
Blocked by #293
