### ISSUE TITLE
Migrate Collections

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#296]
Create an API endpoint, and associated services, that enables the migration of works from Scholarsphere 3 to Scholarsphere 4.

## WDLL

1. New API endpoint 
2. CreateCollectionService or something similar to PublishNewWork for works
3. Documentation

## Questions

1. What about collections with limited visibility, i.e. any collection that is not PSU-only or Public?
_All collections have public visibility regardless of what it was in Scholarsphere 3 or any ACLs_
2. Preserve all existing ACLs? _Yes, but they are enforced for edit rights_
3. Do we create a collection if all of its members are not present? _No_

**Comment by DanCoughlin** [comment]
We need to make sure we have migrated DOI's for collections. We will not update anything on DataCite. DOI field needs to be available on the collection and migrate the value, on migration we will not have the metadata update process.

**Comment by awead** [comment]
See #315 for additional work with DOIs
