### ISSUE TITLE
Migrating DOIs from Scholarsphere 3

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#315]
DOIs are inconsistently applied in Scholarsphere 3. Their formats range from:

* https://doi.org/10.18113/S1KW2H
* 10.1038/srep21619
* doi:10.18113/S1964W
* http://dx.doi.org/10.1080/17496535.2017.1318411
* https://onlinelibrary.wiley.com/doi/abs/10.1002/ccd.25073
* https://doi.org/10.1002/9781444367072.wbiee826
* DOI: 10.1080/0194262X.2015.1102676

Is anything with "doi" in it an official DOI? Some also don't have the doi prefix but the minting authority ID, ex. 12.1234. Should migrate those as well?

## WDLL

1. Procedure for determining which identifiers are actual DOIs that we want to migate
2. Migrate DOI identifiers to the DOI field
3. Migrate any other identifiers to the identifier field
4. Apply this to both collections and works

**Comment by DanCoughlin** [comment]
DOIs that we created we will move to the work-level DOI, DOIs created by other places will be migrated to the identifier field (which is where it is now).

**Comment by awead** [comment]
We seem to have two main DOI prefixes: 10.18113 and 10.26207. The latter is more recent, and is listed under our DataCite account: https://doi.datacite.org/repositories/psu.scholar/prefixes

The 18113 prefix is NOT listed as one of our prefixes, but they are there. If you search for an DOI minted with that prefix it will show up in our DataCite account page.

Based on this, I'm going to surmise that the DOIs we want to migrate to the DOI field are only the ones that have either of these two prefixes. @srerickson can you verify this for me?

**Comment by awead** [comment]
We're migrating prefixes 10.18113 and 10.26207.
