### ISSUE TITLE
Return nil for missing files

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#317]
When migrating works, if the file set has a missing file, we should return nil. Currently, this is raising an error:
```
undefined method `uri' for nil:NilClass
/opt/heracles/deploy/scholarsphere/releases/20200518151259/app/services/file_set_disk_location.rb:10:in `initialize'
```
If we return nil, the work will migrate to a draft state and we can decide what to do with it later. In some cases, the files may not be recoverable. See https://scholarsphere.psu.edu/concern/generic_works/dnc580m898

**Comment by DanCoughlin** [comment]
Yes return nil, works will be migrated in draft status

**Comment by awead** [comment]
Fixed in https://github.com/psu-stewardship/scholarsphere/commit/263b70e41545f095db8f28cc9b29834cec7dca64
