### ISSUE TITLE
Migrating multiple rights

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#331]
SS3 has works with multiple rights. How should be migrate that?

## WDLL

* migrate rights from SS3 to SS4 appropriately
* address cases in which works have multiple rights statements

We need to know a mapping, to know what combinations exist and similar to Resource Types. We will come up with a map.

**Comment by awead** [comment]
@awead will figure out how many there are and if we can fix them in SS3.

**Comment by awead** [comment]
@srerickson these are the works with multiple rights:
✅ https://scholarsphere.psu.edu/concern/generic_works/dz010q056
✅ https://scholarsphere.psu.edu/concern/generic_works/c534fp085
✅ https://scholarsphere.psu.edu/concern/generic_works/c821gj930
✅ https://scholarsphere.psu.edu/concern/generic_works/9g54xh68r
✅ https://scholarsphere.psu.edu/concern/generic_works/dn39x160k
✅ https://scholarsphere.psu.edu/concern/generic_works/c534fp106
✅ https://scholarsphere.psu.edu/concern/generic_works/zg64tm085
✅ https://scholarsphere.psu.edu/concern/generic_works/z029p483f
✅ https://scholarsphere.psu.edu/concern/generic_works/x346f3474
✅ https://scholarsphere.psu.edu/concern/generic_works/x346f346v
✅ https://scholarsphere.psu.edu/concern/generic_works/8623j6166
✅ https://scholarsphere.psu.edu/concern/generic_works/sx61dm45j
✅ https://scholarsphere.psu.edu/concern/generic_works/s4655g68s
✅ https://scholarsphere.psu.edu/concern/generic_works/5712mq552
✅ https://scholarsphere.psu.edu/concern/generic_works/qf85nb41q
✅ https://scholarsphere.psu.edu/concern/generic_works/qj72p7249
✅ https://scholarsphere.psu.edu/concern/generic_works/pz50gw24h
✅ https://scholarsphere.psu.edu/concern/generic_works/6t053f984
✅ https://scholarsphere.psu.edu/concern/generic_works/x346d661d
✅ https://scholarsphere.psu.edu/concern/generic_works/x346d662p
✅ https://scholarsphere.psu.edu/concern/generic_works/5712mx65j
✅ https://scholarsphere.psu.edu/concern/generic_works/tx31qh71t
✅ https://scholarsphere.psu.edu/concern/generic_works/s7526c50k
✅ https://scholarsphere.psu.edu/concern/generic_works/4q77fr46p
✅ https://scholarsphere.psu.edu/concern/generic_works/3f462544p
✅ https://scholarsphere.psu.edu/concern/generic_works/05741r73v
✅ https://scholarsphere.psu.edu/concern/generic_works/x346dx108
✅ https://scholarsphere.psu.edu/concern/generic_works/pn89d6699
✅ https://scholarsphere.psu.edu/concern/generic_works/ht24wj56k
✅ https://scholarsphere.psu.edu/concern/generic_works/5712mv79g
✅ https://scholarsphere.psu.edu/concern/generic_works/2r36tx66j
✅ https://scholarsphere.psu.edu/concern/generic_works/02870v98g
✅ https://scholarsphere.psu.edu/concern/generic_works/t148fh30g
✅ https://scholarsphere.psu.edu/concern/generic_works/rv042t078
✅ https://scholarsphere.psu.edu/concern/generic_works/nv935302r
✅ https://scholarsphere.psu.edu/concern/generic_works/wh246s31g
✅ https://scholarsphere.psu.edu/concern/generic_works/w6634366r
✅ https://scholarsphere.psu.edu/concern/generic_works/8910jt66t
✅ https://scholarsphere.psu.edu/concern/generic_works/5712mx762
✅ https://scholarsphere.psu.edu/concern/generic_works/5712mm71t
✅ https://scholarsphere.psu.edu/concern/generic_works/2r36tx63q

**Comment by awead** [comment]
@srerickson Here are all the unique combinations of rights. Note that these are in order, so it may be possible to just take the last, most recent rights statement for those works with multiples ones:
```
http://creativecommons.org/licenses/by-nc-sa/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://creativecommons.org/licenses/by-nc-sa/3.0/us/,http://creativecommons.org/licenses/by/3.0/us/"
http://creativecommons.org/licenses/by-nc/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://creativecommons.org/licenses/by-nc/3.0/us/,http://creativecommons.org/licenses/by-sa/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://creativecommons.org/licenses/by-nd/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://creativecommons.org/licenses/by-sa/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://creativecommons.org/licenses/by/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://creativecommons.org/publicdomain/mark/1.0/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://creativecommons.org/publicdomain/zero/1.0/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
http://www.europeana.eu/portal/rights/rr-r.html,http://creativecommons.org/licenses/by-nc-nd/3.0/us/"
https://creativecommons.org/licenses/by/4.0/,http://www.europeana.eu/portal/rights/rr-r.html"
```

**Comment by srerickson** [comment]
Not sure if this works, but here is csv with the mapping:

```
"http://creativecommons.org/licenses/by-nc-sa/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",http://creativecommons.org/licenses/by-nc-sa/3.0/us/
"http://creativecommons.org/licenses/by-nc-sa/3.0/us/,http://creativecommons.org/licenses/by/3.0/us/",http://creativecommons.org/licenses/by/3.0/us/
"http://creativecommons.org/licenses/by-nc/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/""",http://creativecommons.org/licenses/by-nc/3.0/us/
"http://creativecommons.org/licenses/by-nc/3.0/us/,http://creativecommons.org/licenses/by-sa/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",https://creativecommons.org/licenses/by-nc/3.0/us/
"http://creativecommons.org/licenses/by-nd/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",http://creativecommons.org/licenses/by-nd/3.0/us/
"http://creativecommons.org/licenses/by-sa/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",http://creativecommons.org/licenses/by-sa/3.0/us/
"http://creativecommons.org/licenses/by/3.0/us/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",http://creativecommons.org/licenses/by/3.0/us/
"http://creativecommons.org/publicdomain/mark/1.0/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",http://creativecommons.org/publicdomain/mark/1.0/
"http://creativecommons.org/publicdomain/zero/1.0/,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",http://creativecommons.org/publicdomain/zero/1.0/
"http://www.europeana.eu/portal/rights/rr-r.html,http://creativecommons.org/licenses/by-nc-nd/3.0/us/",http://creativecommons.org/licenses/by-nc-nd/3.0/us/
"https://creativecommons.org/licenses/by/4.0/,http://www.europeana.eu/portal/rights/rr-r.html",https://creativecommons.org/licenses/by/4.0/
```

**Comment by awead** [comment]
Fixed in https://github.com/psu-stewardship/scholarsphere/pull/1648

**Comment by awead** [comment]
First one on list isn't migrating.

**Comment by awead** [comment]
I've updated the above list of links with the latest records from Scholarsphere 3 production.

**Comment by awead** [comment]
The last two remaining works with multiple rights have been fixed in SS3 and now migrated correctly over to version 4.
