### ISSUE TITLE
Works without a resource type

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#349]
There are little over 1,500 works without a resource type. This is likely because resource type was not required until later releases of Scholarsphere.

Since resource type is used to determine work type in SS4, and that field is required, we're going to need to assign some kind of work type to a work that doesn't have a designated resource type. The easiest way to do this would be to add an "unknown" option to the Work model's list of available work types, and make that the work type for migrated works that have no resource type.

IMPORTANT: we must make sure that the unknown option is NOT included in the dropdown?

**Comment by srerickson** [comment]
I think an "unknown" resource type for these works is a good idea but it shouldn't appear as an option for new works.
