### ISSUE TITLE
Creating an empty collection with errors

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#365]
I can successfully create an empty collection if there are no errors with my metadata. However, if omit the title, which is required, or enter an un-parseable published date, I get:

`undefined method 'map' for nil:NilClass` on on the `app/views/dashboard/collections/_form.html.erb` template.

**Comment by rschenk** [comment]
Both this and #365 will go away once we implement the final UI, with the search-solr-for-a-work means of adding works to collections. However, both of these were easy to fix, so I took care of them
