### ISSUE TITLE
Fail build if code coverage cannot be sent

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#370]
Code coverage is not being sent to Code Climate. We're getting:

```
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
 ```

This is probably due to a bug with Code Climate and the latest SimpleCov gem.

## WDLL

* downgrade SimpleCov so that coverage reports work 
* ensure any future builds with fail if the report is NOT sent to CC

**Comment by whereismyjetpack** [comment]
we exit with rpsec exit code in the script, we should probably `set -e` in the script so it bails on any failure?
