### ISSUE TITLE
Migrate Analytics Data

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#379]
We are migrating our previous analytics from Google to our own solution. The current database has records for every assets, even those that haven't been viewed. We will only be counting records for those assets that have a view.

**Comment by awead** [comment]
## WDLL

We will export that data out of SS3 _after_ migration is completed, then import into SS4. The export process will account for file vs. work views, and the changes in identifiers.

* rake task to export existing statistics out of SS3 in an appropriate format (CSV, json, etc) that includes:
    1 . Work views: the sum of all work views and views of any contained files for a given day
    2. Downloads: downloads for each file for a given day
* import task for SS4 that takes the exported file and imports the data into the database
    * the import task should account for noid-to-UUID translation
