### ISSUE TITLE
Monthly Report

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#380]
Make sure our monthly report is being run to let users know their download counts.

**Comment by awead** [comment]
You can preview the email here: https://scholarsphere-4.test/rails/mailers/actor_mailer/monthly_stats

And will need to add some statistics for the previous month. By default, the previous uses the first Actor in the system. If you running locally, login to a clean instance and you'll be the first actor. Upload a file and then add some stats:

``` ruby
ViewStatistic.create(date: Time.zone.now.last_month, count: 10, resource: FileResource.first) 
```
