### ISSUE TITLE
SS3 migration: concatenate multiple description fields into a single value

### ISSUE THREAD

**Issue by rschenk** [psu-stewardship/scholarsphere-4#384]
In SS4 we've made WorkVersion#description into a single-valued field. In order to migrate, we'll need to concatenate any multiple descriptions that are in SS3 into a single value, much like we did for [publication dates](https://github.com/psu-stewardship/scholarsphere/blob/migration/lib/scholarsphere/migration/work.rb#L24)

**Comment by awead** [comment]
Fixed in https://github.com/psu-stewardship/scholarsphere/commit/20c7fd0a6872e2bf50917e49aec77d57f8991e5b
