### ISSUE TITLE
Work Type Icons

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#386]
We need icons for work types, to be used when listing works/collections (browse, dashboard, etc.). We don't need an icon for each work type, just a few general one. I think the following would be sufficient:

- Journal Article / Conference Proceeding
- Book / Book Chapter
- Audio / Video
- Image
- Map
- Poster / Presentation
- Data Set
- Software / Source Code

**Comment by DanCoughlin** [comment]
We will start with the glyphicons for this purpose.
