### ISSUE TITLE
Redis instance for caching

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#401]
With #400, we'll need an additional Redis instance to handle our session cache. In using a second instance, we can leverage LRU caching for better performance.

## WDLL

* second Redis instance (configured for caching)
* default expiration of 24 hours

**Comment by whereismyjetpack** [comment]
@awead based off our conversation in slack this morning i think this issue can be closed. It's easy enough to spin up a caching server when the time comes, i think right now it's probably premature optimization.
