### ISSUE TITLE
ActionView::Template::Error (undefined method `title' for nil:NilClass)

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-stewardship/scholarsphere-4#425]
when visiting this work `//resources/cb98bbcf-2a13-4638-91c3-c1c778cac610` rails throws the error above. 

1.) https://scholarsphere-migration.dsrd.libraries.psu.edu/resources/cb98bbcf-2a13-4638-91c3-c1c778cac610

2.) https://app.datadoghq.com/apm/trace/8844229904587825234?colorBy=service&env=migration&graphType=span_list&shouldShowLegend=true&sort=time&spanID=8925952396436761481

**Comment by awead** [comment]
The collection has one work, which is unpublished. Therefore:

```
> collection.works.first.latest_published_version
=> nil
```

We should suppress listing unpublished works for migrated collections, and disallow adding unpublished works to collections.

**Comment by awead** [comment]
This appears to have been fixed in #473, but the issue still exists in the dashboard collection view page. However, that page should go away with #492.
