### ISSUE TITLE
Version navigation on work resource view

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#464]
When looking at older versions of a work, we should include a 'warning' banner that indicates you are looking at an older version with a link to the most recent version.

<img width="701" alt="Screen Shot 2020-08-14 at 9 46 02 AM" src="https://user-images.githubusercontent.com/398837/90257755-93964600-de15-11ea-987b-5f97127f4bcf.png">

**Comment by rschenk** [comment]
A couple visual options I mocked up:

## 1
![view-current-version-1](https://user-images.githubusercontent.com/14730/90432238-3cec6e80-e098-11ea-9c92-67197a4a7206.png)

## 2
![view-current-version-2](https://user-images.githubusercontent.com/14730/90432245-3e1d9b80-e098-11ea-9c5b-2b00968f1ed4.png)

**Comment by awead** [comment]
Option 2 is more consistent with the way we’re displaying other similar kinds of info statements like logins and deletions. So I’m in favor of that. But we could restyle those flash messages throughout.

**Comment by bdezray** [comment]
I also like version 2. Thanks for sharing Ryan!

**Comment by binkylush** [comment]
I agree - option 2 gets my vote!
