### ISSUE TITLE
Downloads Email - needs to be fixed

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#469]
There is language in the monthly reports email that directs users to features/pages that are not yet implemented. We need to update the language.

**Comment by whereismyjetpack** [comment]
<img width="680" alt="Screen Shot 2020-08-14 at 10 07 39 AM" src="https://user-images.githubusercontent.com/3694886/90258167-233bf480-de16-11ea-9bc3-c51d7ff2a4e0.png">

example of current rendered email: 

- contact us link goes to /contact which isn't implemented in scholarsphere-4
- dashboard link goes to /dashboard which doesn't appear to be a personalized dashboard in scholarsphere-4
- opt out steps need reworked, ideally just an 'unsubscribe' link?
- other wording tweaks if needed.

**Comment by srerickson** [comment]
I copy and pasted the [current user stats email](https://github.com/psu-stewardship/scholarsphere/blob/master/app/views/user_mailer/user_stats_email.html.erb) and modified the text. The erb stuff will need to be changed but I'll leave that to @awead 

```erb
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
  </head>
<body>
  <h1><%= t('statistic.user_stats.heading', date: Date.today.last_month.strftime('%B')) %></h1>
   <p>Dear <%= @presenter.user.name %>, <br />
      You had <%= @presenter.file_downloads %> new downloads last month across your <%= @presenter.total_files %> deposited work
      in <%= t('sufia.product_name') %>.
   </p>
  <p>Interested in sharing, archiving, and preserving other work? Consider depositing any of the following in
    <a href="https://scholarsphere.psu.edu/"><%= t('sufia.product_name') %></a></p>
  <ul>
    <li>Articles: Check <a href="http://www.sherpa.ac.uk/romeo/index.php">SHERPA/RoMEO</a> to determine which version of
        an article you can archive.
    </li>
    <li>Datasets</li>
    <li>Videos</li>
    <li>Software and analysis code</li>
    <li>Book chapters: Check your publishing agreement to see if you can deposit a contributed chapter.</li>
    <li>Books: Consider
      <a href="https://www.authorsalliance.org/resources/rights-reversion-portal/">regaining copyright</a>
      from your publisher so you can deposit an out-of-print book. You can also deposit any book that is openly licensed,
      such as an open access monograph bearing one of the Creative Commons licenses.
    </li>
  </ul>
</body>
</html>
```

**Comment by srerickson** [comment]
We don't need this by launch, just by early December. (Actually, if we miss one monthly stats emails, it's not the end of the world).
