### ISSUE TITLE
Add identity information in actor search results

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#553]
Add IDs such as Penn State and Orcid to the search results when adding additional creators.

## WDLL

If there's a PSU ID, show it. If there's an Orchid, show that. Otherwise, nil.

**Comment by rschenk** [comment]
@awead We need something to differentiate what these various identifiers mean. I don't think most people will realize that "abc123" is a PSU-ID while "1234-1234-1234-1234" is an Orcid. 

I reckon we could do something like

```
abc123@psu
psu:abc123

orcid:1234-1234-1234-1234
```

![Screen Shot 2020-10-21 at 11 01 11 AM](https://user-images.githubusercontent.com/14730/96738478-c2d4b080-138c-11eb-8763-4341e3c173e3.png)

**Comment by awead** [comment]
@rschenk We could style it up a bit, maybe make a table? Or at least try to have some separation, like right-justifying the ids. But yeah, have: "Access Account: agw13" and "Orchid: 1234-1234-1234-1234".

**Comment by rschenk** [comment]
Cool, ok that works for me.

Unfortunately it is not possible to style this like a table, because the r ows are generated by Algolia, but I do think I could pull the ids all the way to the right. :+1:
