### ISSUE TITLE
Map our work_type metadata field to DataCite's resourceTypeGeneral

### ISSUE THREAD

**Issue by rschenk** [psu-stewardship/scholarsphere-4#576]
DataCite requires us to provide a value for the field `resourceTypeGeneral`. I need a mapping that translates our `work_type` to DataCite's.

This needs to be completed before we release the DOI minting UI

Our list is below:
```
article
audio
book
capstone_project
collection
conference_proceeding
dataset
dissertation
image
journal
map_or_cartographic_material
masters_culminating_experience
masters_thesis
other
part_of_book
poster
presentation
project
report
research_paper
software_or_program_code
thesis
unspecified
video
```

**Comment by srerickson** [comment]
I took a stab at this a while back. Take a look at this and tell me if if helps:
https://docs.google.com/spreadsheets/d/1wGVdGFIfsJOC-nVHPzYEAdYgfpadSPgRwEQ7xsBOFQo/edit#gid=372862448

**Comment by rschenk** [comment]
Sweet! Looks good

**Comment by rschenk** [comment]
@srerickson We are missing three entries from this list:
`["collection", "thesis", "unspecified"]` are all valid Work Types that have no corresponding row in the spreadsheet you linked to above

**Comment by srerickson** [comment]
@rschenk, I updated the spreadsheet with those entries.
