### ISSUE TITLE
Show screen wireframe

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#59]
Need a wire page for the main record that is specific to the user. Blacklight has it's own show page, we have another show page for the user that is working on version of an object. 
Basically one page is backed by postgres and inside "your dashboard"
We have a second page that is backed by Solr and in search results

Do we want two versions of this and if so, what should they look like in wireframes.

**Comment by srerickson** [comment]
I am closing this as the "show" page for works and collections can based (for now) on the SS3 layout.
