### ISSUE TITLE
Update k8s process so we don't have to invoke  /vault/secrets/config

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#590]
When logging into a k8s Rails instance via `kubectl`, we need to run `source /vault/secrets/config` in order to get console access. This should be done automatically without having to run it.

## WDLL

I can run:

    $ kubectl exec -it [pod] /bin/bash

Then from inside the pod:

    $ bundle exec rails c

And it "just works" ;)

**Comment by awead** [comment]
@whereismyjetpack I wasn't sure where this was supposed to go, so I'm just leaving it here so I don't forget about it.

**Comment by whereismyjetpack** [comment]
there is a wrapper script that may help. try this 

```
 k exec -it scholarsphere-qa-646bb8459d-zrnm2 /app/bin/vaultshell
```

**Comment by awead** [comment]
Works for me. I'll leave this open until one of us can update the wiki.

**Comment by whereismyjetpack** [comment]
Did you want this dropped in the gh wiki?

**Comment by awead** [comment]
yes, but I'm now noticing that we didn't have that information in there to begin with. If you think it's a good place for it, then the wiki would be the easiest. But, since it's not really a Scholarsphere-specific thing, maybe it ought to go someplace else?

**Comment by whereismyjetpack** [comment]
we had this stuff in our dlt sites page, and i fear that's where things go to get lost. I can put ss specific stuff in the gh wiki, since that's probably where a developer is going to go first

**Comment by whereismyjetpack** [comment]
https://github.com/psu-stewardship/scholarsphere-4/wiki/kubernetes we can add to this as we see fit!
