### ISSUE TITLE
Open Access and Penn State public works should be accessible without a login

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#600]
Visiting open access resources, when not logged in, is prompting Azure authentication. It should not, and the page should render without any require authentication.

**Comment by whereismyjetpack** [comment]
This may be due to the migration configuration, historically we would protect non production deployments with IP allowlists, however, in the new environment we require a logged in user. let me test this and get back to you

**Comment by awead** [comment]
@whereismyjetpack It's weird. If I logout, I can reload the page fine, but if I use a different browser or a private window, I get the login prompt.

**Comment by whereismyjetpack** [comment]
your session with the proxy is probably still valid, that's probably a good way to test though, it appears that it's working as intended!

**Comment by awead** [comment]
False alarm. Penn State works should be accessible without a login. Only their files are inaccessible. See https://github.com/psu-stewardship/scholarsphere-4/blob/master/doc/architecture/decisions/0006-public-discovery-access.md
