### ISSUE TITLE
Migration Data Report

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#61]
We need to identify a couple types of works in current ScholarSphere, that are potentially problematic. For example, how many works do we have that have files with multiple versions. How many works do we have with multiple files. Other potentially difficult migration relationships or properties that may exist, but let's find out if there are "a lot" of these files existing or if there are a few of them then we may be able to migrate them manually.

## Parameters
* works having many versions of files
* works in collections
* works with a single file
* works with permissions set it a specific group

## TODO
Seth will add more potential problematic works for us to look at and add to this ticket.

**Comment by DanCoughlin** [comment]
How many files have permissions set to a specific group? Guessing this feature isn't widely used.

**Comment by DanCoughlin** [comment]
If we can get more context around some of these, for example:
if there are files with versions, is the file a README or is it a data file (a README may not be nearly as important)

**Comment by awead** [comment]
Add to report:
* files with different permissions than the parent work
* multi-file works with different permissions among the files
* counts of embargoed and leased works, including dates of expiration
* works with read groups other than public or registered

**Comment by awead** [comment]
Results are report here: https://docs.google.com/spreadsheets/d/1sWbpvdOKNKG4lCdNuqKDYKOIs9RpKEsJQXRukgfcT8M/edit?usp=sharing
