### ISSUE TITLE
Documentation for psu-authproxy setup

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#63]
When working locally, we can run an instance of psu-authproxy in order to mimic authentication. In order to get it working, it requires some setup. We need to document this for new devs or existing ones who can't remember all the steps.

What Done Looks Like:
* a wiki page in this repo (it can also reference a page in the authproxy repo)
* steps to install authproxy
* steps to configure authproxy locally
* steps to get scholarsphere-4 working with your local authproxy service

**Comment by whereismyjetpack** [comment]
I got a start on this: https://github.com/psu-stewardship/scholarsphere-4/wiki/psu-authproxy
