### ISSUE TITLE
Incorrect options in OminiAuth::Strategies::Psu

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#64]
In OminiAuth::Strategies::Psu, the `authorize_path` option should be `authorize_url` instead. See https://github.com/oauth-xx/oauth2/blob/master/lib/oauth2/client.rb#L36

Currently, if we specify a different path, it will have no effect.

**Comment by awead** [comment]
@whereismyjetpack Can you take a look at this? Perhaps `authorize_url` ought to be an ENV option?

**Comment by whereismyjetpack** [comment]
I sure can. We grabbed that code from an oauth example, so i'm wondering what changed. I think we should set authorize_url and default it with the specified path. I don't anticipate it changing but if it does we should be able to hijack it
