### ISSUE TITLE
User model should store first and last name instead of just "name"

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#66]
Our authorization application is returning first and last name. We should store these returned values as given name and surname in our local database for future use.

**Comment by whereismyjetpack** [comment]
we make this "nice" in the oauth app from givenName and sn, 

```
        last_name: ldap_record[:sn][0],
        first_name: ldap_record[:givenname][0],
```
This was just me following gut instinct, that 'first name' and 'last name' are more meaningful than givenName and sn.

**Comment by awead** [comment]
@whereismyjetpack Actually, the reverse is more appropriate. We've found that users from non-western cultures might have a different concept of what a "first" name is, so we use given vs. surname (or family) name to capture that distinction. If LDAP is returning given and sur, I'd rather keep that consistent. The oauth app should return given and sur, and then Scholarsphere should save them as such.

**Comment by awead** [comment]
See psu-stewardship/psu-authproxy#4

**Comment by whereismyjetpack** [comment]
I've mended this. we should now be returning `surname` and `given_name` from the user endpoint.
