### ISSUE TITLE
Testing browser integration in DroneCI

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#67]
Feature tests can use a headless browser for javascript and other integration testing. Currently, this is not implemented in our CI environment. Tests such as `publish_new_work_spec.rb` will only run in the local testing environment. We need to implement a reliable way of running these tests using a complete browser environment.

What Done Looks Like:
Remove the `unless: ci_build?` from any existing feature tests and the DroneCI build will pass.

**Comment by whereismyjetpack** [comment]
Fixed via #74
