### ISSUE TITLE
Collections Functionality

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#91]
This is a placeholder issue for discussing features of "Collections" in ScholarSphere 4. Collections are important but I think there is an opportunity to rethink them a bit to clarify how they are different from Works. Also, they might be helpful in use cases that ScholarSphere doesn't currently address very well. 

### PSU Common Collections

One such use case is the need for users to associate their work with a particular category or set of works. Currently we can do this with keywords or resource types but we may want other kinds of groups—or collections, if you will. The recent "Masters Culminating Experience" is an example of what I mean: The need is for students to be able to add their work to a set of works that administrators can keep track of. This is currently implemented as a new resource type called "Masters Culminating Experience", but this solution is kind of a kludge since "Masters Culminating Experience" isn't really a specific genre and its meaning is fairly specific to the PSU context. ("Masters Culminating Experience" doesn't correspond to one of DataCite's resource types, for example). A better option would be implement Masters Culminating Experience works as an open or common collection that anyone at PSU can add work their to—also, administrators could kick works out of the Collection if they need to (i.e., without modifying the underling Work).

Other thoughts to come.

**Comment by DanCoughlin** [comment]
Collections will operate as they currently do in ScholarSphere.
