### ISSUE TITLE
Canonical URLs

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#92]
What is the canonical url for a work or a work version? These would be the urls that DOIs resolve to, or are otherwise the unique url for a given work or work version. All published works and their versions would have one.

## Options

1. Use Blacklight's catalog controller, with the UUID:
`/catalog/552b93f8-5997-4d5e-9954-a42b7e5bf7fa`
2. Use a different pathname, and/or a different kind of identifier:
`/resources/1234asdf`

###  Architectural Considerations

With option 1, we'd be invested more into Blacklight's Solr-based representation of the resource. This has the advantage of already being there, but means we'd need to maintain the Solr representation along with the Postgres one, if we're intending to still continue using it for display purposes.

Option 2 would allow us to put the work representation in Postgres, and relegate Blacklight's activity to searching only.

**Comment by DanCoughlin** [comment]
Seth and Briana would like to go to Option 2 and UUIDs (12/9/2019)

**Comment by awead** [comment]
## TODO
* revert fe666eb0d62603cb1098bce4b69938b7f1124186 and generate the actual public url
