### ISSUE TITLE
Policy and AWS 

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#98]
Discussion to understand library policy for storing data in scholarsphere and making sure we are meeting that policy within our AWS implementation.

**Comment by DanCoughlin** [comment]
Conversation to be had with Paul and EIT on technical details and cost
Conversation for Seth, Dann, Dan, and Briana to discuss library preservation policy and how that correlates to AWS implementation.

**Comment by whereismyjetpack** [comment]
Notes from meeting with EIT:

AWS Implementation Option:
Primary bucket located in us-east-1, a bucket in a single region is backed by 3 availability zones and has 99.99999999999% durability, with 99.9% availability

As items are placed in this bucket, they are replicated into another bucket (presently in us-west-2) Delete events are not replicated, and versioning is enabled on both buckets. 

After 2 days, items placed in the west bucket are "frozen" (moved to glacier) for DR purposes only.

**Comment by DanCoughlin** [comment]
Sketch of discussion on this.
![IMG_6325](https://user-images.githubusercontent.com/398837/71262218-34774480-230d-11ea-9d1a-38bcc06ac4a9.jpg)

**Comment by srerickson** [comment]
I just met with Nathan Tallman about storage/preservation planning. He strongly encouraged replication to at least one non-AWS storage endpoint, which I think makes sense.
